# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Encryption.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'Encryption.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x45ncryption.proto\x12\x08hbase.pb\"W\n\nWrappedKey\x12\x11\n\talgorithm\x18\x01 \x02(\t\x12\x0e\n\x06length\x18\x02 \x02(\r\x12\x0c\n\x04\x64\x61ta\x18\x03 \x02(\x0c\x12\n\n\x02iv\x18\x04 \x01(\x0c\x12\x0c\n\x04hash\x18\x05 \x01(\x0c\x42\x43\n*org.apache.hadoop.hbase.protobuf.generatedB\x10\x45ncryptionProtosH\x01\xa0\x01\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Encryption_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n*org.apache.hadoop.hbase.protobuf.generatedB\020EncryptionProtosH\001\240\001\001'
  _globals['_WRAPPEDKEY']._serialized_start=30
  _globals['_WRAPPEDKEY']._serialized_end=117
# @@protoc_insertion_point(module_scope)
