# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: FS.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'FS.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08\x46S.proto\x12\x08hbase.pb\"*\n\x17HBaseVersionFileContent\x12\x0f\n\x07version\x18\x01 \x02(\t\"e\n\tReference\x12\x10\n\x08splitkey\x18\x01 \x02(\x0c\x12(\n\x05range\x18\x02 \x02(\x0e\x32\x19.hbase.pb.Reference.Range\"\x1c\n\x05Range\x12\x07\n\x03TOP\x10\x00\x12\n\n\x06\x42OTTOM\x10\x01\x42;\n*org.apache.hadoop.hbase.protobuf.generatedB\x08\x46SProtosH\x01\xa0\x01\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'FS_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n*org.apache.hadoop.hbase.protobuf.generatedB\010FSProtosH\001\240\001\001'
  _globals['_HBASEVERSIONFILECONTENT']._serialized_start=22
  _globals['_HBASEVERSIONFILECONTENT']._serialized_end=64
  _globals['_REFERENCE']._serialized_start=66
  _globals['_REFERENCE']._serialized_end=167
  _globals['_REFERENCE_RANGE']._serialized_start=139
  _globals['_REFERENCE_RANGE']._serialized_end=167
# @@protoc_insertion_point(module_scope)
