# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: MultiRowMutation.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'MultiRowMutation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Client_pb2 as Client__pb2
import HBase_pb2 as HBase__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16MultiRowMutation.proto\x12\x08hbase.pb\x1a\x0c\x43lient.proto\x1a\x0bHBase.proto\"\"\n MultiRowMutationProcessorRequest\"#\n!MultiRowMutationProcessorResponse\"\x95\x01\n\x11MutateRowsRequest\x12\x31\n\x10mutation_request\x18\x01 \x03(\x0b\x32\x17.hbase.pb.MutationProto\x12\x13\n\x0bnonce_group\x18\x02 \x01(\x04\x12\r\n\x05nonce\x18\x03 \x01(\x04\x12)\n\x06region\x18\x04 \x01(\x0b\x32\x19.hbase.pb.RegionSpecifier\"\x14\n\x12MutateRowsResponse2b\n\x17MultiRowMutationService\x12G\n\nMutateRows\x12\x1b.hbase.pb.MutateRowsRequest\x1a\x1c.hbase.pb.MutateRowsResponseBL\n*org.apache.hadoop.hbase.protobuf.generatedB\x16MultiRowMutationProtosH\x01\x88\x01\x01\xa0\x01\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MultiRowMutation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n*org.apache.hadoop.hbase.protobuf.generatedB\026MultiRowMutationProtosH\001\210\001\001\240\001\001'
  _globals['_MULTIROWMUTATIONPROCESSORREQUEST']._serialized_start=63
  _globals['_MULTIROWMUTATIONPROCESSORREQUEST']._serialized_end=97
  _globals['_MULTIROWMUTATIONPROCESSORRESPONSE']._serialized_start=99
  _globals['_MULTIROWMUTATIONPROCESSORRESPONSE']._serialized_end=134
  _globals['_MUTATEROWSREQUEST']._serialized_start=137
  _globals['_MUTATEROWSREQUEST']._serialized_end=286
  _globals['_MUTATEROWSRESPONSE']._serialized_start=288
  _globals['_MUTATEROWSRESPONSE']._serialized_end=308
  _globals['_MULTIROWMUTATIONSERVICE']._serialized_start=310
  _globals['_MULTIROWMUTATIONSERVICE']._serialized_end=408
# @@protoc_insertion_point(module_scope)
