# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: PingProtocol.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'PingProtocol.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12PingProtocol.proto\"\r\n\x0bPingRequest\"\x1c\n\x0cPingResponse\x12\x0c\n\x04pong\x18\x01 \x02(\t\"\x0e\n\x0c\x43ountRequest\"\x1e\n\rCountResponse\x12\r\n\x05\x63ount\x18\x01 \x02(\x05\"%\n\x15IncrementCountRequest\x12\x0c\n\x04\x64iff\x18\x01 \x02(\x05\"\'\n\x16IncrementCountResponse\x12\r\n\x05\x63ount\x18\x01 \x02(\x05\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"!\n\rHelloResponse\x12\x10\n\x08response\x18\x01 \x01(\t\"\r\n\x0bNoopRequest\"\x0e\n\x0cNoopResponse2\xe5\x01\n\x0bPingService\x12#\n\x04ping\x12\x0c.PingRequest\x1a\r.PingResponse\x12&\n\x05\x63ount\x12\r.CountRequest\x1a\x0e.CountResponse\x12<\n\tincrement\x12\x16.IncrementCountRequest\x1a\x17.IncrementCountResponse\x12&\n\x05hello\x12\r.HelloRequest\x1a\x0e.HelloResponse\x12#\n\x04noop\x12\x0c.NoopRequest\x1a\r.NoopResponseBJ\n6org.apache.hadoop.hbase.coprocessor.protobuf.generatedB\nPingProtos\x88\x01\x01\xa0\x01\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PingProtocol_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n6org.apache.hadoop.hbase.coprocessor.protobuf.generatedB\nPingProtos\210\001\001\240\001\001'
  _globals['_PINGREQUEST']._serialized_start=22
  _globals['_PINGREQUEST']._serialized_end=35
  _globals['_PINGRESPONSE']._serialized_start=37
  _globals['_PINGRESPONSE']._serialized_end=65
  _globals['_COUNTREQUEST']._serialized_start=67
  _globals['_COUNTREQUEST']._serialized_end=81
  _globals['_COUNTRESPONSE']._serialized_start=83
  _globals['_COUNTRESPONSE']._serialized_end=113
  _globals['_INCREMENTCOUNTREQUEST']._serialized_start=115
  _globals['_INCREMENTCOUNTREQUEST']._serialized_end=152
  _globals['_INCREMENTCOUNTRESPONSE']._serialized_start=154
  _globals['_INCREMENTCOUNTRESPONSE']._serialized_end=193
  _globals['_HELLOREQUEST']._serialized_start=195
  _globals['_HELLOREQUEST']._serialized_end=223
  _globals['_HELLORESPONSE']._serialized_start=225
  _globals['_HELLORESPONSE']._serialized_end=258
  _globals['_NOOPREQUEST']._serialized_start=260
  _globals['_NOOPREQUEST']._serialized_end=273
  _globals['_NOOPRESPONSE']._serialized_start=275
  _globals['_NOOPRESPONSE']._serialized_end=289
  _globals['_PINGSERVICE']._serialized_start=292
  _globals['_PINGSERVICE']._serialized_end=521
# @@protoc_insertion_point(module_scope)
