# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: RPC.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'RPC.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Tracing_pb2 as Tracing__pb2
import HBase_pb2 as HBase__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tRPC.proto\x12\x08hbase.pb\x1a\rTracing.proto\x1a\x0bHBase.proto\"<\n\x0fUserInformation\x12\x16\n\x0e\x65\x66\x66\x65\x63tive_user\x18\x01 \x02(\t\x12\x11\n\treal_user\x18\x02 \x01(\t\"\xc8\x01\n\x10\x43onnectionHeader\x12,\n\tuser_info\x18\x01 \x01(\x0b\x32\x19.hbase.pb.UserInformation\x12\x14\n\x0cservice_name\x18\x02 \x01(\t\x12\x1e\n\x16\x63\x65ll_block_codec_class\x18\x03 \x01(\t\x12#\n\x1b\x63\x65ll_block_compressor_class\x18\x04 \x01(\t\x12+\n\x0cversion_info\x18\x05 \x01(\x0b\x32\x15.hbase.pb.VersionInfo\"\x1f\n\rCellBlockMeta\x12\x0e\n\x06length\x18\x01 \x01(\r\"|\n\x11\x45xceptionResponse\x12\x1c\n\x14\x65xception_class_name\x18\x01 \x01(\t\x12\x13\n\x0bstack_trace\x18\x02 \x01(\t\x12\x10\n\x08hostname\x18\x03 \x01(\t\x12\x0c\n\x04port\x18\x04 \x01(\x05\x12\x14\n\x0c\x64o_not_retry\x18\x05 \x01(\x08\"\xc9\x01\n\rRequestHeader\x12\x0f\n\x07\x63\x61ll_id\x18\x01 \x01(\r\x12&\n\ntrace_info\x18\x02 \x01(\x0b\x32\x12.hbase.pb.RPCTInfo\x12\x13\n\x0bmethod_name\x18\x03 \x01(\t\x12\x15\n\rrequest_param\x18\x04 \x01(\x08\x12\x30\n\x0f\x63\x65ll_block_meta\x18\x05 \x01(\x0b\x32\x17.hbase.pb.CellBlockMeta\x12\x10\n\x08priority\x18\x06 \x01(\r\x12\x0f\n\x07timeout\x18\x07 \x01(\r\"\x83\x01\n\x0eResponseHeader\x12\x0f\n\x07\x63\x61ll_id\x18\x01 \x01(\r\x12.\n\texception\x18\x02 \x01(\x0b\x32\x1b.hbase.pb.ExceptionResponse\x12\x30\n\x0f\x63\x65ll_block_meta\x18\x03 \x01(\x0b\x32\x17.hbase.pb.CellBlockMetaB<\n*org.apache.hadoop.hbase.protobuf.generatedB\tRPCProtosH\x01\xa0\x01\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RPC_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n*org.apache.hadoop.hbase.protobuf.generatedB\tRPCProtosH\001\240\001\001'
  _globals['_USERINFORMATION']._serialized_start=51
  _globals['_USERINFORMATION']._serialized_end=111
  _globals['_CONNECTIONHEADER']._serialized_start=114
  _globals['_CONNECTIONHEADER']._serialized_end=314
  _globals['_CELLBLOCKMETA']._serialized_start=316
  _globals['_CELLBLOCKMETA']._serialized_end=347
  _globals['_EXCEPTIONRESPONSE']._serialized_start=349
  _globals['_EXCEPTIONRESPONSE']._serialized_end=473
  _globals['_REQUESTHEADER']._serialized_start=476
  _globals['_REQUESTHEADER']._serialized_end=677
  _globals['_RESPONSEHEADER']._serialized_start=680
  _globals['_RESPONSEHEADER']._serialized_end=811
# @@protoc_insertion_point(module_scope)
