# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: RSGroup.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'RSGroup.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Table_pb2 as Table__pb2
import HBase_pb2 as HBase__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rRSGroup.proto\x12\x08hbase.pb\x1a\x0bTable.proto\x1a\x0bHBase.proto\"g\n\x0bRSGroupInfo\x12\x0c\n\x04name\x18\x01 \x02(\t\x12%\n\x07servers\x18\x04 \x03(\x0b\x32\x14.hbase.pb.ServerName\x12#\n\x06tables\x18\x03 \x03(\x0b\x32\x13.hbase.pb.TableNameBC\n*org.apache.hadoop.hbase.protobuf.generatedB\rRSGroupProtosH\x01\x88\x01\x01\xa0\x01\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RSGroup_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n*org.apache.hadoop.hbase.protobuf.generatedB\rRSGroupProtosH\001\210\001\001\240\001\001'
  _globals['_RSGROUPINFO']._serialized_start=53
  _globals['_RSGROUPINFO']._serialized_end=156
# @@protoc_insertion_point(module_scope)
