# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: test_rpc_service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'test_rpc_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import test_pb2 as test__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16test_rpc_service.proto\x1a\ntest.proto2\x8a\x02\n\x14TestProtobufRpcProto\x12/\n\x04ping\x12\x12.EmptyRequestProto\x1a\x13.EmptyResponseProto\x12-\n\x04\x65\x63ho\x12\x11.EchoRequestProto\x1a\x12.EchoResponseProto\x12\x30\n\x05\x65rror\x12\x12.EmptyRequestProto\x1a\x13.EmptyResponseProto\x12\x30\n\x05pause\x12\x12.PauseRequestProto\x1a\x13.EmptyResponseProto\x12.\n\x04\x61\x64\x64r\x12\x12.EmptyRequestProto\x1a\x12.AddrResponseProtoBL\n.org.apache.hadoop.hbase.ipc.protobuf.generatedB\x14TestRpcServiceProtos\x88\x01\x01\xa0\x01\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'test_rpc_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n.org.apache.hadoop.hbase.ipc.protobuf.generatedB\024TestRpcServiceProtos\210\001\001\240\001\001'
  _globals['_TESTPROTOBUFRPCPROTO']._serialized_start=39
  _globals['_TESTPROTOBUFRPCPROTO']._serialized_end=305
# @@protoc_insertion_point(module_scope)
