# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: VisibilityLabels.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'VisibilityLabels.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Client_pb2 as Client__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16VisibilityLabels.proto\x12\x08hbase.pb\x1a\x0c\x43lient.proto\"F\n\x17VisibilityLabelsRequest\x12+\n\x08visLabel\x18\x01 \x03(\x0b\x32\x19.hbase.pb.VisibilityLabel\"1\n\x0fVisibilityLabel\x12\r\n\x05label\x18\x01 \x02(\x0c\x12\x0f\n\x07ordinal\x18\x02 \x01(\r\"H\n\x18VisibilityLabelsResponse\x12,\n\x06result\x18\x01 \x03(\x0b\x32\x1c.hbase.pb.RegionActionResult\"-\n\x0fSetAuthsRequest\x12\x0c\n\x04user\x18\x01 \x02(\x0c\x12\x0c\n\x04\x61uth\x18\x02 \x03(\x0c\"0\n\x12UserAuthorizations\x12\x0c\n\x04user\x18\x01 \x02(\x0c\x12\x0c\n\x04\x61uth\x18\x02 \x03(\r\"J\n\x17MultiUserAuthorizations\x12/\n\tuserAuths\x18\x01 \x03(\x0b\x32\x1c.hbase.pb.UserAuthorizations\"\x1f\n\x0fGetAuthsRequest\x12\x0c\n\x04user\x18\x01 \x02(\x0c\".\n\x10GetAuthsResponse\x12\x0c\n\x04user\x18\x01 \x02(\x0c\x12\x0c\n\x04\x61uth\x18\x02 \x03(\x0c\"\"\n\x11ListLabelsRequest\x12\r\n\x05regex\x18\x01 \x01(\t\"#\n\x12ListLabelsResponse\x12\r\n\x05label\x18\x01 \x03(\x0c\x32\x91\x03\n\x17VisibilityLabelsService\x12R\n\taddLabels\x12!.hbase.pb.VisibilityLabelsRequest\x1a\".hbase.pb.VisibilityLabelsResponse\x12I\n\x08setAuths\x12\x19.hbase.pb.SetAuthsRequest\x1a\".hbase.pb.VisibilityLabelsResponse\x12K\n\nclearAuths\x12\x19.hbase.pb.SetAuthsRequest\x1a\".hbase.pb.VisibilityLabelsResponse\x12\x41\n\x08getAuths\x12\x19.hbase.pb.GetAuthsRequest\x1a\x1a.hbase.pb.GetAuthsResponse\x12G\n\nlistLabels\x12\x1b.hbase.pb.ListLabelsRequest\x1a\x1c.hbase.pb.ListLabelsResponseBL\n*org.apache.hadoop.hbase.protobuf.generatedB\x16VisibilityLabelsProtosH\x01\x88\x01\x01\xa0\x01\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'VisibilityLabels_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n*org.apache.hadoop.hbase.protobuf.generatedB\026VisibilityLabelsProtosH\001\210\001\001\240\001\001'
  _globals['_VISIBILITYLABELSREQUEST']._serialized_start=50
  _globals['_VISIBILITYLABELSREQUEST']._serialized_end=120
  _globals['_VISIBILITYLABEL']._serialized_start=122
  _globals['_VISIBILITYLABEL']._serialized_end=171
  _globals['_VISIBILITYLABELSRESPONSE']._serialized_start=173
  _globals['_VISIBILITYLABELSRESPONSE']._serialized_end=245
  _globals['_SETAUTHSREQUEST']._serialized_start=247
  _globals['_SETAUTHSREQUEST']._serialized_end=292
  _globals['_USERAUTHORIZATIONS']._serialized_start=294
  _globals['_USERAUTHORIZATIONS']._serialized_end=342
  _globals['_MULTIUSERAUTHORIZATIONS']._serialized_start=344
  _globals['_MULTIUSERAUTHORIZATIONS']._serialized_end=418
  _globals['_GETAUTHSREQUEST']._serialized_start=420
  _globals['_GETAUTHSREQUEST']._serialized_end=451
  _globals['_GETAUTHSRESPONSE']._serialized_start=453
  _globals['_GETAUTHSRESPONSE']._serialized_end=499
  _globals['_LISTLABELSREQUEST']._serialized_start=501
  _globals['_LISTLABELSREQUEST']._serialized_end=535
  _globals['_LISTLABELSRESPONSE']._serialized_start=537
  _globals['_LISTLABELSRESPONSE']._serialized_end=572
  _globals['_VISIBILITYLABELSSERVICE']._serialized_start=575
  _globals['_VISIBILITYLABELSSERVICE']._serialized_end=976
# @@protoc_insertion_point(module_scope)
